### ISSUE TITLE
CSV and email html reporting

### ISSUE THREAD

**Issue by ly2ly** [lmangani/sentinl#449]
Hello, 
I have 2 questions about reporting, they can be (I think) some interesting improvements. 
- Is it possible or have you plan possibility to send kibana discover csv report by mail?
- About watcher action html email, I try to send a dashboad Iframe 
![iframe1](https://user-images.githubusercontent.com/7696009/41119704-fc561c64-6a82-11e8-9adf-a500c5dbc7e3.png)
I got an infinite loading page in my email. 
![iframe2](https://user-images.githubusercontent.com/7696009/41119715-055e1ec4-6a83-11e8-9974-677bb2547a41.png)
But when I put Iframe code inside a html file, I can see my dashboard. So is it possible to put html code of the html email inside a separate html file?
![iframe3](https://user-images.githubusercontent.com/7696009/41119735-166b295a-6a83-11e8-9020-9902e667f598.png)

Thanks

**Comment by lmangani** [comment]
Hi @ly2ly 

#### Is it possible or have you plan possibility to send kibana discover csv report by mail?
I'm not sure I understand the question - could you provide a specific indicator as of what you're referring to?

##### About watcher action html email, I try to send a dashboad Iframe
I don't think this would ever work and its not due to SENTINL, but rather what a client would accept. As far as I know, the email HTML format would not allow this to take place in good clients.

**Comment by ly2ly** [comment]
Hello,
Thanks for you anwser and sorry for late.

> Is it possible or have you plan possibility to send kibana discover csv report by mail?
When you make a selection of fiel in kibana discover you can generate a csv reporting of you selection.
Right now I don't now if Sentinl is able to send this report by mail. If not, do you plan this possibility?

![image](https://user-images.githubusercontent.com/7696009/41491175-158b9776-70e7-11e8-8146-d000e55f0b5e.png)

**Comment by bienensenf** [comment]
+1 for CSV reports
