### ISSUE TITLE
BRAVE TESTERS WANTED 🥇 

### ISSUE THREAD

**Issue by lmangani** [lmangani/sentinl#522]
To All SENTINL Users: 

We have some new exciting features and ideas in store for upcoming 6.x versions and we'd like to form an Alpha group of brave community users for testing and providing early feedback in the coming months and weeks - the ideal entry requirements in order of importance are:

- Time & Patience as things might not always work out!
- Experience with SENTINL & Alerting in general
- Decent Elasticsearch and Kibana background
- Communication skills to report bugs, logs and ideas clearly
- Ability to query and play with with Timelion or Kable

Participants will be fully credited and hopefully become proud contributors of the platform 👍 

Interested? Thanks in advance for supporting Open Source - Post a comment or message me!

**Comment by havlan** [comment]
I'll try to participate as long as I feel like I have the time :+1: 
Hope as many as possible would consider! It will be fun :+1: :100:

**Comment by arifurreza** [comment]
Interested

**Comment by Arun-Ghosh** [comment]
I am interested too... Definitely will try my best.

**Comment by ShalbafZadeh** [comment]
I'm In

**Comment by mehrdad1985** [comment]
i'm in !

**Comment by lmangani** [comment]
This is a nice first group! I'm preparing a dedicated Wiki page with some experiments :)

**Comment by havlan** [comment]
@lmangani could you explain the different use cases of the experimental features?
Especially the sql translator, or how you plan to integrate it into existing features.

**Comment by lmangani** [comment]
@havlan right now its free field. We do have some planned usecase applications, but right now we're sharing those components to let users test with the possibilities they open and provide feedback

**Comment by fbaligand** [comment]
Hi @lmangani ,

Some feedback about last published version 6.X.X-4 : 
- I like the watcher wizzard to quickly bootstrap a watcher. 
- I love the fact that we can easily migrate a "wizzard" watcher to an "advanced" watcher. I find it essential, as with quick wizzard, I can't define a "query" to filter concerned documents by the watcher.
- that said, once I am on "advanced" watcher editor, I'm very sad to have only JSON editor and no way to edit some parts with a UI, or to go back to the wizzard editor. I clearly miss the previous UI where I can edit the raw JSON, as I can edit some parts like with a UI, using tabs. This is especially true for actions, particularly when I should edit email body or http post body. When it is a field in a raw JSON, that is particularly uncomfortable because line breaks and double quotes have to be encoded. This is not easy to write, neither to read.
- Personally, I clearly like the idea of the previous UI : one editor (not a wizzard and an advanced), and the ease to use at any moment either raw editor either UI editor.
- So here's my suggestion! Have one editor with several tabs : 
-- first one named "wizzard" with the existing wizzard UI
-- second named "advanced" with raw JSON editor
-- another for each particular part of watcher : 
--- trigger (with the existing wizzard UI)
--- input (raw JSON or a wizzard type UI)
--- condition (with a UI : combobox to select condition type, and when it is a script, a textarea to write the script, so that user has not to encode break lines and double quotes)
--- transform (with a UI : especially a simple textarea to edit script easily with break lines and double quotes)
--- actions (with the existing wizzard UI)

My suggestion is probably to ambitious. But this was the idea of the previous UI that I loved !

What do you think about ?
